### PR TITLE
impl: set data type

### PR DESCRIPTION
**Pull request by yoshihiro-shu**
## overview
Implement the Set data type.

- SADD key member [member ...]
- SCARD key
- SMEMBERS key
- SREM key member [member ...]

## Issue
- https://github.com/Kirov7/CouloyDB/issues/23

### CODE REVIEW

**Comment by bigboss2063** [comment]
Hi, Yoshi.

Sorry to tell you that our subsequent data structures need to be implemented in transactions, just like the Hash data type.

You can refer to `txnHash.go` to implement, no need to implement functions in db.go.

I can give you some advice if you'd like to modify it: 

1. Adding a new DataType Set, and do not use the Hash.
2. Adding a new Index Type in index.go like:`type setIndex map[string]meta.MemTable`.
3. The key of Set's meta.MemTable should not use the value of Set. You can distinguish them by the hash value of the values in the Set.

I hope you can keep in touch with us during the development process, so as not to have disagreements between us.🤣

**Comment by yoshihiro-shu** [comment]
@bigboss2063 
Could you review my code please?

**Comment by bigboss2063** [comment]
> @bigboss2063 
> I refer `txnHash.go` and implement it.
> Could you review my code please?

Of course! I'll do it when I back to home.

**Comment by bigboss2063** [comment]
Can you resolve the conflicts first.

**Comment by bigboss2063** [comment]
There is another question. If you use the Value of member as the Key in the setIndex, it means that we are actually storing all the values in memory, but we are not a memory database. 

I have an idea to use the hash value of "member's Value" as the Key, corresponding to each "member's DataPos." If you have a better idea, please feel free to suggest it.

**Comment by yoshihiro-shu** [comment]
@bigboss2063 
Thank you for your review.

>I have an idea to use the hash value of "member's Value" as the Key, corresponding to each "member's DataPos." If you have a better idea, please feel free to suggest it.

I'd like to respect your idea.
Do you mean like this data structure?

```golang
type (
	setIndex    map[string]memberIndex
	memberIndex map[string]meta.MemTable
)
```

**Comment by bigboss2063** [comment]
> @bigboss2063 Thank you for your review.
> 
> > I have an idea to use the hash value of "member's Value" as the Key, corresponding to each "member's DataPos." If you have a better idea, please feel free to suggest it.
> 
> I'd like to respect your idea. Do you mean like this data structure?
> 
> ```go
> type (
> 	setIndex    map[string]memberIndex
> 	memberIndex map[string]meta.MemTable
> )
> ```

No, even this data struct still let the Value store in memory.

You could do such things:

1. first, Value -> hash code, maybe use the murmurhash or fnv?
2. use that hash code as the key of MemTable to get a data pos.
3. So you can only store data pos in memory, rather than the whole Value.

**Comment by yoshihiro-shu** [comment]
@bigboss2063 
Thank you for your advise!
I implemented it based on your review.

**Comment by bigboss2063** [comment]
Could you please help with one last revision? I think SADD and the like should be changed to SAdd, because for the Go language, this is the method name.

**Comment by bigboss2063** [comment]
And you spelled `updateSetIndex` as `udpateSetIndex` XD

**Comment by yoshihiro-shu** [comment]
@yoshihiro-shu 
Thank you for your review!
I fix it.

**Comment by bigboss2063** [comment]
LGTM!

**Pull request merged**
