### PR TITLE
feat: add HStrLen, HKEYS, HVALS, HLEN for Hash

### PR DESCRIPTION
**Pull request by 99HU**

### CODE REVIEW

**Comment by bigboss2063** [comment]
There is a problem in HLEN.Since the index will be updated after the transaction is committed, this implementation is wrong, and the writing in pendingWrites needs to be considered.

**Comment by bigboss2063** [comment]
Beside, there are problems in `TestTxn_HKEYSAVALUES`.
First, the test function name is unintelligible, I suggest you can name it `TestTxn_HKEYS_VALUES`.
Second, map is an unordered data structure, you cannot use the results returned by HGetALL to judge whether the results of HKeys and HValues are correct.

**Comment by 99HU** [comment]
the problem of  HLEN ，the writing in pendingWrites， has been considered. TestTxn_HLEN has been added.

**Comment by 99HU** [comment]
thanks for your advince,i have changed the function name as TestTxn_HKEYS_HVALUES and add sort before Hkeys 、Hvals tests.

**Comment by bigboss2063** [comment]
Last two problems:
1. The naming convention for functions in Golang is camel case. Please change 'bytes_sort' to 'BytesSort' and place it in the 'bytex.go' file. This way, in the future, when you need to sort a byte array, you can use it again.
2. Your test cases are all performed within a single transaction. Try dividing them into multiple transactions to test whether the data in the consistent view is being considered.

Thanks!

**Comment by bigboss2063** [comment]
LGTM.

**Pull request merged**
